


name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Bubblewrap
        run: |
          npm install -g @bubblewrap/cli
          yes | bubblewrap init --manifest="https://dizzar-mw.github.io/filirupaints/manifest.json"
          bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: filirupaints-release
          path: "*.apk"
